spring.application.name=demo

# jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# DB Connection information

# 1. main
main.datasource.hikari.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
main.datasource.hikari.jdbc-url=jdbc:sqlserver://localhost:1433;databaseName=demo;encrypt=false;trustServerCertificate=true
main.datasource.hikari.username=sa
main.datasource.hikari.password=!siop5689951
main.datasource.hikari.connection-test-query=SELECT 1

# 2. sub
sub.datasource.hikari.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
sub.datasource.hikari.jdbc-url=jdbc:sqlserver://192.168.7.123:10000;databaseName=smartship_db;encrypt=false;trustServerCertificate=true
sub.datasource.hikari.username=offshore
sub.datasource.hikari.password=Cisco!23
sub.datasource.hikari.connection-test-query=SELECT 1

